### ISSUE TITLE
Branding : Boston Made Logo EPIC

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/creative-team-workflow#2]

**Comment by sebastianebarb** [comment]
Contact: crystal.torman@boston.gov

First round deadline: October (Manufacturing month )
- [ ] Branding, logo icons
- [ ] Web page (on boston.gov)
- [ ]  2-3 Videos promoting the brand and local businesses 
- [ ]  Announcement of Boston Made

Second round deadline: November (holiday shopping)
- [ ] First round of ads
- [ ] Tie in for 5 on Main
- [ ]  2-3 Videos promoting the brand and local businesses

**Comment by sebastianebarb** [comment]
We have narrowed it down to two logos: the hexagon and the customs house. 

We were wondering if it would be possible to change the customs house logo to say Made in Boston instead of Boston Made and perhaps do it in two rows so that the logo isn't super spread out.

Let me know if you have any questions. Thanks so much for all your help!

**Comment by sebastianebarb** [comment]
[BOSTON MADE V2.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46cabba917adade9a2c89b66e46ba2d665043761260ea62864c7b96aea157851585a1bab44505d11fcac8b2aa6b46d258e5a58e4c3714d36976345f3e5db55ea43a82a994e82bcbd8f48c3e03b26ef8d864c3f1b1755.pdf)
